import { type Quotation, type Room, type FloorPlanRoom } from "../../types";

// Rooms data
const rooms: Room[] = [
	{
		id: "hab-p",
		name: "Hab. P",
		emoji: "🛏",
		dimensions: { width: 2.56, length: 2.66, height: 2.22 },
		area: 6.81,
		wallArea: 23.02,
		perimeter: 10.44,
		variant: "teal",
		materials: [
			{
				id: "p-piso",
				name: "Porcelanato 60×60",
				detail: "Piso habitación principal",
				category: "piso",
				quantity: 19,
				unit: "und",
				unitPrice: 35000,
				total: 665000,
			},
			{
				id: "p-pared",
				name: "Pintura vinilo",
				detail: "2 manos en paredes",
				category: "pared",
				quantity: 23.02,
				unit: "m²",
				unitPrice: 15000,
				total: 345300,
			},
			{
				id: "p-techo",
				name: "Pintura cielorraso",
				detail: "1 mano",
				category: "techo",
				quantity: 6.81,
				unit: "m²",
				unitPrice: 12000,
				total: 81720,
			},
			{
				id: "p-zocalo",
				name: "Zócalo PVC",
				detail: "Perímetro habitación",
				category: "revestimiento",
				quantity: 10.44,
				unit: "m",
				unitPrice: 15000,
				total: 156600,
			},
		],
		subtotal: 1248620,
		laborTotal: 450000,
	},
	{
		id: "hab-r",
		name: "Hab. R",
		emoji: "🛏",
		dimensions: { width: 2.66, length: 3.5, height: 2.22 },
		area: 9.31,
		wallArea: 27.35,
		perimeter: 12.32,
		variant: "green",
		materials: [
			{
				id: "r-piso",
				name: "Porcelanato 60×60",
				detail: "Piso habitación R",
				category: "piso",
				quantity: 26,
				unit: "und",
				unitPrice: 35000,
				total: 910000,
			},
			{
				id: "r-pared",
				name: "Pintura vinilo",
				detail: "2 manos en paredes",
				category: "pared",
				quantity: 27.35,
				unit: "m²",
				unitPrice: 15000,
				total: 410250,
			},
			{
				id: "r-techo",
				name: "Pintura cielorraso",
				detail: "1 mano",
				category: "techo",
				quantity: 9.31,
				unit: "m²",
				unitPrice: 12000,
				total: 111720,
			},
			{
				id: "r-zocalo",
				name: "Zócalo PVC",
				detail: "Perímetro habitación",
				category: "revestimiento",
				quantity: 12.32,
				unit: "m",
				unitPrice: 15000,
				total: 184800,
			},
		],
		subtotal: 1616770,
		laborTotal: 520000,
	},
	{
		id: "hab-a",
		name: "Hab. A",
		emoji: "🛏",
		dimensions: { width: 2.51, length: 3.5, height: 2.22 },
		area: 8.79,
		wallArea: 26.57,
		perimeter: 12.02,
		variant: "red",
		materials: [
			{
				id: "a-piso",
				name: "Porcelanato 60×60",
				detail: "Piso habitación A",
				category: "piso",
				quantity: 25,
				unit: "und",
				unitPrice: 35000,
				total: 875000,
			},
			{
				id: "a-pared",
				name: "Pintura vinilo",
				detail: "2 manos en paredes",
				category: "pared",
				quantity: 26.57,
				unit: "m²",
				unitPrice: 15000,
				total: 398550,
			},
			{
				id: "a-techo",
				name: "Pintura cielorraso",
				detail: "1 mano",
				category: "techo",
				quantity: 8.79,
				unit: "m²",
				unitPrice: 12000,
				total: 105480,
			},
			{
				id: "a-zocalo",
				name: "Zócalo PVC",
				detail: "Perímetro habitación",
				category: "revestimiento",
				quantity: 12.02,
				unit: "m",
				unitPrice: 15000,
				total: 180300,
			},
		],
		subtotal: 1559330,
		laborTotal: 500000,
	},
	{
		id: "sala",
		name: "Sala",
		emoji: "🛋",
		dimensions: { width: 2.67, length: 3.54, height: 2.22 },
		area: 9.45,
		wallArea: 27.66,
		perimeter: 12.42,
		variant: "purple",
		materials: [
			{
				id: "s-piso",
				name: "Porcelanato 60×60",
				detail: "Piso sala",
				category: "piso",
				quantity: 27,
				unit: "und",
				unitPrice: 35000,
				total: 945000,
			},
			{
				id: "s-pared",
				name: "Pintura vinilo",
				detail: "2 manos en paredes",
				category: "pared",
				quantity: 27.66,
				unit: "m²",
				unitPrice: 15000,
				total: 414900,
			},
			{
				id: "s-techo",
				name: "Pintura cielorraso",
				detail: "1 mano",
				category: "techo",
				quantity: 9.45,
				unit: "m²",
				unitPrice: 12000,
				total: 113400,
			},
			{
				id: "s-zocalo",
				name: "Zócalo PVC",
				detail: "Perímetro sala",
				category: "revestimiento",
				quantity: 12.42,
				unit: "m",
				unitPrice: 15000,
				total: 186300,
			},
		],
		subtotal: 1659600,
		laborTotal: 530000,
	},
	{
		id: "bano",
		name: "Baño",
		emoji: "🛁",
		dimensions: { width: 1.8, length: 1.81, height: 2.22 },
		area: 3.26,
		wallArea: 16.06,
		perimeter: 7.22,
		variant: "blue",
		materials: [
			{
				id: "b-piso",
				name: "Baldosa antideslizante",
				detail: "Piso baño",
				category: "piso",
				quantity: 10,
				unit: "und",
				unitPrice: 8500,
				total: 85000,
			},
			{
				id: "b-pared",
				name: "Cerámica pared",
				detail: "Enchape paredes",
				category: "revestimiento",
				quantity: 16.06,
				unit: "m²",
				unitPrice: 50000,
				total: 803000,
			},
			{
				id: "b-techo",
				name: "Techo PVC",
				detail: "Lámina + perfilería",
				category: "techo",
				quantity: 3.26,
				unit: "m²",
				unitPrice: 28000,
				total: 91280,
			},
			{
				id: "b-imp",
				name: "Impermeabilizante",
				detail: "Antes de enchape",
				category: "impermeabilizacion",
				quantity: 3.26,
				unit: "m²",
				unitPrice: 25000,
				total: 81500,
			},
			{
				id: "b-puerta",
				name: "Puerta HDF",
				detail: "Marco + bisagras",
				category: "carpinteria",
				quantity: 1,
				unit: "und",
				unitPrice: 380000,
				total: 380000,
			},
		],
		subtotal: 1440780,
		laborTotal: 480000,
	},
	{
		id: "lavadero",
		name: "Lavadero",
		emoji: "🫧",
		dimensions: { width: 0.8, length: 1.8, height: 2.22 },
		area: 1.44,
		wallArea: 11.59,
		perimeter: 5.2,
		variant: "purple",
		materials: [
			{
				id: "l-piso",
				name: "Baldosa antideslizante",
				detail: "Piso lavadero",
				category: "piso",
				quantity: 5,
				unit: "und",
				unitPrice: 8500,
				total: 42500,
			},
			{
				id: "l-pared",
				name: "Cerámica pared",
				detail: "Enchape paredes",
				category: "revestimiento",
				quantity: 11.59,
				unit: "m²",
				unitPrice: 50000,
				total: 579500,
			},
			{
				id: "l-techo",
				name: "Techo PVC",
				detail: "Lámina + perfilería",
				category: "techo",
				quantity: 1.44,
				unit: "m²",
				unitPrice: 28000,
				total: 40320,
			},
		],
		subtotal: 662320,
		laborTotal: 220000,
	},
	{
		id: "cocina",
		name: "Cocina",
		emoji: "🍳",
		dimensions: { width: 2.66, length: 2.0, height: 2.22 },
		area: 5.32,
		wallArea: 20.73,
		perimeter: 9.32,
		variant: "gold",
		materials: [
			{
				id: "c-piso",
				name: "Porcelanato 60×60",
				detail: "Piso cocina",
				category: "piso",
				quantity: 15,
				unit: "und",
				unitPrice: 35000,
				total: 525000,
			},
			{
				id: "c-pared",
				name: "Pintura vinilo",
				detail: "2 manos en paredes",
				category: "pared",
				quantity: 20.73,
				unit: "m²",
				unitPrice: 15000,
				total: 310950,
			},
			{
				id: "c-techo",
				name: "Pintura cielorraso",
				detail: "1 mano",
				category: "techo",
				quantity: 5.32,
				unit: "m²",
				unitPrice: 12000,
				total: 63840,
			},
			{
				id: "c-sal",
				name: "Salpicadero cerámica",
				detail: "Zona trabajo",
				category: "revestimiento",
				quantity: 3.5,
				unit: "m²",
				unitPrice: 55000,
				total: 192500,
			},
			{
				id: "c-puerta",
				name: "Puerta HDF",
				detail: "Marco + bisagras",
				category: "carpinteria",
				quantity: 1,
				unit: "und",
				unitPrice: 380000,
				total: 380000,
			},
		],
		subtotal: 1472290,
		laborTotal: 470000,
	},
	{
		id: "pasillo",
		name: "Pasillo",
		emoji: "🚪",
		dimensions: { width: 2.51, length: 0.78, height: 2.22 },
		area: 1.96,
		wallArea: 14.55,
		perimeter: 6.58,
		variant: "teal",
		materials: [
			{
				id: "pa-piso",
				name: "Porcelanato 60×60",
				detail: "Piso pasillo",
				category: "piso",
				quantity: 6,
				unit: "und",
				unitPrice: 35000,
				total: 210000,
			},
			{
				id: "pa-pared",
				name: "Pintura vinilo",
				detail: "2 manos en paredes",
				category: "pared",
				quantity: 14.55,
				unit: "m²",
				unitPrice: 15000,
				total: 218250,
			},
			{
				id: "pa-techo",
				name: "Pintura cielorraso",
				detail: "1 mano",
				category: "techo",
				quantity: 1.96,
				unit: "m²",
				unitPrice: 12000,
				total: 23520,
			},
		],
		subtotal: 451770,
		laborTotal: 150000,
	},
];

// Floor plan rooms
export const apartmentV1FloorPlan: FloorPlanRoom[] = [
	{
		id: "hab-p",
		name: "HAB. P",
		x: 0,
		y: 0,
		width: 2.56,
		height: 2.66,
		variant: "teal",
		area: 6.81,
		dimensions: "2.56×2.66",
	},
	{
		id: "bano",
		name: "BAÑO",
		x: 2.56,
		y: 0,
		width: 1.8,
		height: 1.81,
		variant: "blue",
		area: 3.26,
		dimensions: "1.80×1.81",
	},
	{
		id: "lavadero",
		name: "LAV",
		x: 4.36,
		y: 0,
		width: 0.8,
		height: 1.8,
		variant: "purple",
		area: 1.44,
		dimensions: "0.80×1.80",
	},
	{
		id: "cocina",
		name: "COCINA",
		x: 5.16,
		y: 0,
		width: 2.66,
		height: 2.0,
		variant: "gold",
		area: 5.32,
		dimensions: "2.66×2.00",
	},
	{
		id: "hab-r",
		name: "HAB. R",
		x: 0,
		y: 2.66,
		width: 2.66,
		height: 3.5,
		variant: "green",
		area: 9.31,
		dimensions: "2.66×3.50",
	},
	{
		id: "hab-a",
		name: "HAB. A",
		x: 2.66,
		y: 1.81,
		width: 2.51,
		height: 3.5,
		variant: "red",
		area: 8.79,
		dimensions: "2.51×3.50",
	},
	{
		id: "sala",
		name: "SALA",
		x: 5.17,
		y: 2.0,
		width: 2.67,
		height: 3.54,
		variant: "purple",
		area: 9.45,
		dimensions: "2.67×3.54",
	},
];

// Full quotation
export const apartmentV1Data: Quotation = {
	id: "apartamento-v1",
	title: "APARTAMENTO COMPLETO",
	tag: "Presupuesto de Obra · Bogotá 2026",
	date: new Date("2026-04-18"),
	rooms,
	prices: {
		piso: { material: 35000, manoObra: 20000 },
		pared: { material: 15000, manoObra: 0 },
		techo: { material: 12000, manoObra: 0 },
		electricidad: { punto: 45000 },
		carpinteria: { puerta: 380000 },
		revestimiento: { material: 50000, manoObra: 25000 },
		impermeabilizacion: { material: 25000 },
		imprevistos: 8,
	},
	subtotal: 10111490,
	laborTotal: 3320000,
	unforeseen: 1074519,
	total: 14506009,
	currency: "COP",
};

// Pills for header
export const apartmentV1Pills = [
	{ icon: "📐", label: "8.06 × 6.28 m = 50.6 m²", variant: "teal" as const },
	{ icon: "🛏", label: "3 Habitaciones", variant: "gold" as const },
	{ icon: "🛁", label: "Baño + Lavadero", variant: "blue" as const },
	{ icon: "🍳", label: "Cocina + Sala", variant: "red" as const },
	{ icon: "📏", label: "Alto: 2.22 m", variant: "purple" as const },
];
