import { type Quotation, type FloorPlanRoom } from "../../types";

// Floor plan rooms
export const bathroomV3FloorPlan: FloorPlanRoom[] = [
	{
		id: "bano",
		name: "BAÑO",
		x: 0,
		y: 0,
		width: 6.0,
		height: 2.2,
		variant: "blue",
		area: 13.2,
		dimensions: "6.00×2.20",
	},
];

// Full quotation
export const bathroomV3Data: Quotation = {
	id: "bathroom-v3",
	title: "BAÑO COMPLETO",
	tag: "Presupuesto de Obra · 2026",
	date: new Date("2026-04-18"),
	rooms: [
		{
			id: "bano",
			name: "Baño",
			emoji: "🛁",
			dimensions: { width: 6.0, length: 2.2, height: 2.4 },
			area: 13.2,
			wallArea: 39.36,
			perimeter: 16.4,
			variant: "blue",
			materials: [
				// Piso
				{
					id: "b-piso",
					name: "Baldosa 60×30",
					detail: "Piso antideslizante",
					category: "piso",
					quantity: 88,
					unit: "und",
					unitPrice: 8500,
					total: 748000,
				},
				{
					id: "b-piso-peg",
					name: "Pegante / mortero",
					detail: "Piso",
					category: "piso",
					quantity: 13.2,
					unit: "m²",
					unitPrice: 4500,
					total: 59400,
				},
				{
					id: "b-piso-frag",
					name: "Fragua",
					detail: "Juntas piso",
					category: "piso",
					quantity: 13.2,
					unit: "m²",
					unitPrice: 3500,
					total: 46200,
				},
				// Paredes
				{
					id: "b-pared",
					name: "Baldosa 60×30",
					detail: "Paredes hasta 2.40m",
					category: "revestimiento",
					quantity: 234,
					unit: "und",
					unitPrice: 8500,
					total: 1989000,
				},
				{
					id: "b-pared-peg",
					name: "Pegante / mortero",
					detail: "Paredes",
					category: "revestimiento",
					quantity: 39.36,
					unit: "m²",
					unitPrice: 4500,
					total: 177120,
				},
				{
					id: "b-pared-frag",
					name: "Fragua",
					detail: "Juntas paredes",
					category: "revestimiento",
					quantity: 39.36,
					unit: "m²",
					unitPrice: 3500,
					total: 137760,
				},
				// Techo
				{
					id: "b-techo",
					name: "Techo PVC",
					detail: "Lámina + perfilería",
					category: "techo",
					quantity: 13.2,
					unit: "m²",
					unitPrice: 28000,
					total: 369600,
				},
				// Impermeabilización
				{
					id: "b-imp",
					name: "Impermeabilizante",
					detail: "Antes de enchape",
					category: "impermeabilizacion",
					quantity: 13.2,
					unit: "m²",
					unitPrice: 25000,
					total: 330000,
				},
				// Accesorios
				{
					id: "b-ducha",
					name: "Ducha eléctrica",
					detail: "Con instalación",
					category: "accesorio",
					quantity: 1,
					unit: "und",
					unitPrice: 280000,
					total: 280000,
				},
				{
					id: "b-inodoro",
					name: "Inodoro",
					detail: "Con tanque y accesorios",
					category: "accesorio",
					quantity: 1,
					unit: "und",
					unitPrice: 450000,
					total: 450000,
				},
				{
					id: "b-lavamanos",
					name: "Lavamanos",
					detail: "Con mueble base",
					category: "accesorio",
					quantity: 1,
					unit: "und",
					unitPrice: 350000,
					total: 350000,
				},
				{
					id: "b-espejo",
					name: "Espejo",
					detail: "60×80cm con marco",
					category: "accesorio",
					quantity: 1,
					unit: "und",
					unitPrice: 120000,
					total: 120000,
				},
				{
					id: "b-toallero",
					name: "Toallero",
					detail: "Inoxidable",
					category: "accesorio",
					quantity: 1,
					unit: "und",
					unitPrice: 85000,
					total: 85000,
				},
				{
					id: "b-jabonera",
					name: "Jabonera",
					detail: "Inoxidable",
					category: "accesorio",
					quantity: 1,
					unit: "und",
					unitPrice: 45000,
					total: 45000,
				},
				{
					id: "b-puerta",
					name: "Puerta HDF",
					detail: "Marco + bisagras + cerradura",
					category: "carpinteria",
					quantity: 1,
					unit: "und",
					unitPrice: 380000,
					total: 380000,
				},
			],
			subtotal: 5567080,
			laborTotal: 1800000,
		},
	],
	prices: {
		piso: { material: 8500, manoObra: 18000 },
		pared: { material: 8500, manoObra: 22000 },
		techo: { material: 28000, manoObra: 20000 },
		electricidad: { punto: 45000 },
		carpinteria: { puerta: 380000 },
		revestimiento: { material: 8500, manoObra: 22000 },
		impermeabilizacion: { material: 25000 },
		imprevistos: 8,
	},
	subtotal: 5567080,
	laborTotal: 1800000,
	unforeseen: 589366,
	total: 7956446,
	currency: "COP",
};

// Pills for header
export const bathroomV3Pills = [
	{ icon: "📐", label: "6 × 2.20 m = 13.2 m²", variant: "teal" as const },
	{ icon: "🧱", label: "Baldosa piso + paredes", variant: "gold" as const },
	{ icon: "🏠", label: "Techo PVC", variant: "green" as const },
	{ icon: "🚿", label: "Ducha eléctrica", variant: "red" as const },
];
